### ISSUE TITLE
Merge in ECEInTheHole (jpgualdarrama)'s version

### ISSUE THREAD

**Issue by bobpaw** [KaizokuBento/PokeFarmQoL#23]
Because your post names that fork as the new version, it may be appropriate to either merge in their changes, or at the very least modify the @downloadURL of the main userscript to point to the new version. While I'm not clear on if TamperMonkey does update checks before anything else, the brokenness will at least point users not automatically updated to the forum post in order to get the latest thing. It also might just update to the new one and work.

Another great option might be to add @jpgualdarrama as a contributor to the repo so that they can add all their changes while also providing the updates to users that might otherwise be unaware of them.

**Comment by KaizokuBento** [comment]
Added @jpgualdarrama as contributor.
